/**
 * Le pied « Generated by Claude Code » retiré des issues et des PR (#254).
 *
 * Le proxy des sessions ajoute à chaque description et commentaire qu'elles écrivent par l'API un
 * trait `---`, puis « _Generated by [Claude Code](…)_ ». `sansPied` retire ce pied, avec le trait qui
 * le précède et les lignes vides qui l'en séparent, et rien d'autre ; un texte sans pied revient tel
 * quel, pour n'être pas réécrit.
 *
 *   node retirer-pied.mjs fusion <n>   la PR n, ses commentaires et ses revues, et chaque issue
 *                                      qu'elle ferme (« Close #m »), description et commentaires
 *   node retirer-pied.mjs tout         toutes les issues et PR du dépôt, ouvertes ou fermées
 *
 * Lit `GH_TOKEN` et `GH_REPO` (propriétaire/dépôt). N'appelle que l'API de GitHub : rien d'autre ne
 * s'exécute, rien ne s'extrait d'une PR.
 */
import { fileURLToPath } from 'node:url';

/** Le pied, en fin de texte : blancs, trait, lignes vides, mention en italique, blancs. */
const PIED = /(?:^|\r?\n)[ \t]*(?:\r?\n[ \t]*)*---[ \t]*\r?\n(?:[ \t]*\r?\n)*[ \t]*_Generated by \[Claude Code\]\([^()\s]*\)_[ \t]*(?:\r?\n[ \t]*)*$/;

/** Le texte sans le pied, répété s'il y en a plusieurs à la suite ; tel quel sans pied. */
export function sansPied(texte) {
  if (typeof texte !== 'string') return texte;
  let t = texte;
  for (let avant; avant !== t; ) {
    avant = t;
    t = t.replace(PIED, '');
  }
  return t;
}

/** Les issues qu'une description ferme, par les mots-clés de GitHub (« Close #n », « Fixes #n »…). */
export function issuesFermees(corps) {
  const motif = /\b(?:close[sd]?|fix(?:e[sd])?|resolve[sd]?)\s*:?\s+#(\d+)\b/gi;
  return [...new Set([...(corps ?? '').matchAll(motif)].map((m) => Number(m[1])))];
}

// ─── L'API de GitHub ─────────────────────────────────────────────────────────────────────────────

function client({ jeton, depot, api = 'https://api.github.com', journal = console.log, appeler = fetch }) {
  const entetes = { Authorization: `Bearer ${jeton}`, Accept: 'application/vnd.github+json', 'X-GitHub-Api-Version': '2022-11-28' };
  async function appel(methode, chemin, corps) {
    const r = await appeler(chemin.startsWith('http') ? chemin : `${api}/repos/${depot}/${chemin}`, {
      method: methode,
      headers: corps ? { ...entetes, 'Content-Type': 'application/json' } : entetes,
      body: corps ? JSON.stringify(corps) : undefined,
    });
    if (!r.ok) throw new Error(`${methode} ${chemin} : ${r.status} ${await r.text()}`);
    return { donnees: r.status === 204 ? null : await r.json(), suivant: /<([^>]+)>;\s*rel="next"/.exec(r.headers.get('link') ?? '')?.[1] };
  }
  async function* pages(chemin) {
    let url = `${chemin}${chemin.includes('?') ? '&' : '?'}per_page=100`;
    while (url) {
      const { donnees, suivant } = await appel('GET', url);
      yield* donnees;
      url = suivant;
    }
  }
  let retraits = 0;
  /** Réécrit le texte s'il porte le pied ; un commentaire vidé garderait un corps vide, que GitHub refuse : il reste. */
  async function nettoyer(quoi, texte, methode, chemin, vide = false) {
    const propre = sansPied(texte);
    if (propre === texte || (!propre.trim() && !vide)) return;
    await appel(methode, chemin, { body: propre });
    retraits += 1;
    journal(`Pied retiré : ${quoi}.`);
  }
  return { appel, pages, nettoyer, retraits: () => retraits };
}

/** Description et commentaires d'une issue ou d'une PR ; pour une PR, commentaires de revue et revues aussi. */
async function nettoyerUne(gh, n) {
  const { donnees: issue } = await gh.appel('GET', `issues/${n}`);
  const genre = issue.pull_request ? 'PR' : 'issue';
  await gh.nettoyer(`description de la ${genre} #${n}`, issue.body ?? '', 'PATCH', `issues/${n}`, true);
  for await (const c of gh.pages(`issues/${n}/comments`)) await gh.nettoyer(`commentaire ${c.id} de #${n}`, c.body ?? '', 'PATCH', `issues/comments/${c.id}`);
  if (!issue.pull_request) return issue;
  for await (const c of gh.pages(`pulls/${n}/comments`)) await gh.nettoyer(`commentaire de revue ${c.id} de #${n}`, c.body ?? '', 'PATCH', `pulls/comments/${c.id}`);
  for await (const r of gh.pages(`pulls/${n}/reviews`)) await gh.nettoyer(`revue ${r.id} de #${n}`, r.body ?? '', 'PUT', `pulls/${n}/reviews/${r.id}`, true);
  return issue;
}

/** La PR fusionnée, puis chaque issue qu'elle ferme, lue dans sa description avant nettoyage. */
export async function fusion(gh, n) {
  const pr = await nettoyerUne(gh, n);
  for (const m of issuesFermees(pr.body)) if (m !== n) await nettoyerUne(gh, m);
}

/** Tout le dépôt : les descriptions et les commentaires par la liste du dépôt, puis les revues, PR par PR. */
export async function tout(gh) {
  const prs = [];
  for await (const i of gh.pages('issues?state=all')) {
    await gh.nettoyer(`description de #${i.number}`, i.body ?? '', 'PATCH', `issues/${i.number}`, true);
    if (i.pull_request) prs.push(i.number);
  }
  for await (const c of gh.pages('issues/comments')) await gh.nettoyer(`commentaire ${c.id}`, c.body ?? '', 'PATCH', `issues/comments/${c.id}`);
  for await (const c of gh.pages('pulls/comments')) await gh.nettoyer(`commentaire de revue ${c.id}`, c.body ?? '', 'PATCH', `pulls/comments/${c.id}`);
  for (const n of prs) for await (const r of gh.pages(`pulls/${n}/reviews`)) await gh.nettoyer(`revue ${r.id} de #${n}`, r.body ?? '', 'PUT', `pulls/${n}/reviews/${r.id}`, true);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const [mode, numero] = process.argv.slice(2);
  const { GH_TOKEN: jeton, GH_REPO: depot } = process.env;
  if (!jeton || !depot || !(mode === 'tout' || (mode === 'fusion' && /^\d+$/.test(numero ?? '')))) {
    console.error('usage : GH_TOKEN=… GH_REPO=propriétaire/dépôt node retirer-pied.mjs fusion <n> | tout');
    process.exit(2);
  }
  const gh = client({ jeton, depot });
  await (mode === 'tout' ? tout(gh) : fusion(gh, Number(numero)));
  console.log(`${gh.retraits()} pied(s) retiré(s).`);
}

export { client };
