/**
 * #254 · Le pied « Generated by Claude Code » retiré des issues et des PR : ce qui est retiré, ce
 * qui reste, et quand le nettoyage tourne.
 *
 * Le texte est nettoyé par `retirer-pied.mjs`, joué contre une API de GitHub simulée en mémoire ;
 * le workflow `nettoyage.yml` est joué à blanc (`workflow-a-blanc.mjs`). Que le jeton du job ne
 * déclenche aucun workflow est une règle de GitHub, hors d'atteinte : on vérifie que le job n'en
 * utilise pas d'autre.
 *
 * Tests du codeur de #254, au niveau 4 (D83, #285).
 */
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import test, { describe } from 'node:test';
import { RACINE } from './gardes.mjs';
import { client, fusion, issuesFermees, sansPied, tout } from './retirer-pied.mjs';
import { commande, jouer } from './workflow-a-blanc.mjs';

const PIED = '---\n_Generated by [Claude Code](https://claude.ai/code)_';
const avecPied = (texte) => `${texte}\n\n${PIED}`;

describe('[niveau 4] #254 · ce qui est retiré, ce qui reste', () => {
  test('le pied part avec son trait et les lignes vides qui l’en séparent ; le reste est intact', () => {
    const texte = 'Paroles du porteur.\n\n## Le besoin\n\nUn tableau :\n\n| a | b |\n|---|---|\n\n---\n\nUne section.';
    assert.equal(sansPied(avecPied(texte)), texte);
    assert.equal(sansPied(`${texte}\n\n\n${PIED}\n`), texte);
    assert.equal(sansPied(`${texte}\r\n\r\n---\r\n_Generated by [Claude Code](https://claude.ai/code)_\r\n`), texte);
    assert.equal(sansPied(`${texte}\n---\n\n_Generated by [Claude Code](https://claude.ai/code/session_1)_`), texte);
  });

  test('deux pieds à la suite partent tous deux ; un texte fait du seul pied devient vide', () => {
    assert.equal(sansPied(avecPied(avecPied('Texte.'))), 'Texte.');
    assert.equal(sansPied(PIED), '');
  });

  test('un texte sans pied revient tel quel, et rien d’autre ne part', () => {
    for (const texte of [
      '',
      'Texte.',
      'Texte.\n\n---\n',
      `${PIED}\n\nUne suite après le pied.`,
      'Texte.\n\n---\n_Generated by Claude Code_',
      'Texte.\n\n🤖 Generated with [Claude Code](https://claude.com/claude-code)',
      'Texte.\n\n_Generated by [Claude Code](https://claude.ai/code)_',
    ]) {
      assert.equal(sansPied(texte), texte, JSON.stringify(texte));
    }
  });

  test('les issues fermées se lisent dans la description de la PR', () => {
    assert.deepEqual(issuesFermees('Close #254\n\nFixes #12, resolves: #13 ; voir #14'), [254, 12, 13]);
    assert.deepEqual(issuesFermees(null), []);
  });
});

// ─── Contre une API simulée ──────────────────────────────────────────────────────────────────────

function api() {
  const d = {
    issues: {
      1: { number: 1, body: avecPied('Le besoin #1.') },
      2: { number: 2, body: 'Le besoin #2, sans pied.' },
      3: { number: 3, body: avecPied('Close #1'), pull_request: {} },
      4: { number: 4, body: avecPied('Close #2'), pull_request: {} },
      5: { number: 5, body: avecPied('Un autre besoin.') },
    },
    commentaires: [
      { id: 11, n: 1, body: avecPied('Architecte : spécifié.') },
      { id: 12, n: 3, body: avecPied('Compte rendu.') },
      { id: 13, n: 3, body: PIED },
      { id: 14, n: 5, body: avecPied('Commentaire ailleurs.') },
      { id: 15, n: 1, body: 'Sans pied.' },
    ],
    revues: [
      { id: 21, n: 3, body: avecPied('Un avis de ligne.') },
      { id: 22, n: 4, body: avecPied('Un avis de ligne sur #4.') },
    ],
    avis: [
      { id: 31, n: 3, body: avecPied('Vérifié.') },
      { id: 32, n: 4, body: '' },
    ],
  };
  const écrits = [];
  const json = (x) => new Response(JSON.stringify(x), { status: 200, headers: { 'content-type': 'application/json' } });
  const sans = ({ n, ...x }) => x;
  async function appeler(url, { method, body }) {
    const chemin = new URL(url).pathname.replace(/^\/repos\/o\/r\//, '');
    const corps = body && JSON.parse(body).body;
    const trouver = (liste, id) => liste.find((x) => x.id === Number(id));
    let m;
    if (method === 'GET') {
      if (chemin === 'issues') return json(Object.values(d.issues));
      if (chemin === 'issues/comments') return json(d.commentaires.map(sans));
      if (chemin === 'pulls/comments') return json(d.revues.map(sans));
      if ((m = /^issues\/(\d+)$/.exec(chemin))) return json(d.issues[m[1]]);
      if ((m = /^issues\/(\d+)\/comments$/.exec(chemin))) return json(d.commentaires.filter((c) => c.n === Number(m[1])).map(sans));
      if ((m = /^pulls\/(\d+)\/comments$/.exec(chemin))) return json(d.revues.filter((c) => c.n === Number(m[1])).map(sans));
      if ((m = /^pulls\/(\d+)\/reviews$/.exec(chemin))) return json(d.avis.filter((c) => c.n === Number(m[1])).map(sans));
    }
    écrits.push(`${method} ${chemin}`);
    if (method === 'PATCH' && (m = /^issues\/(\d+)$/.exec(chemin))) d.issues[m[1]].body = corps;
    else if (method === 'PATCH' && (m = /^issues\/comments\/(\d+)$/.exec(chemin))) trouver(d.commentaires, m[1]).body = corps;
    else if (method === 'PATCH' && (m = /^pulls\/comments\/(\d+)$/.exec(chemin))) trouver(d.revues, m[1]).body = corps;
    else if (method === 'PUT' && (m = /^pulls\/\d+\/reviews\/(\d+)$/.exec(chemin))) trouver(d.avis, m[1]).body = corps;
    else return new Response('inconnu', { status: 404 });
    return json({});
  }
  const gh = client({ jeton: 'j', depot: 'o/r', journal: () => {}, appeler });
  return { d, écrits, gh };
}

describe('[niveau 4] #254 · à la fusion et chaque semaine, contre une API simulée', () => {
  test('à la fusion : la PR, ses commentaires et ses revues, et l’issue qu’elle ferme ; rien d’autre', async () => {
    const { d, écrits, gh } = api();
    await fusion(gh, 3);
    assert.deepEqual(écrits.sort(), [
      'PATCH issues/1',
      'PATCH issues/3',
      'PATCH issues/comments/11',
      'PATCH issues/comments/12',
      'PATCH pulls/comments/21',
      'PUT pulls/3/reviews/31',
    ]);
    assert.equal(d.issues[1].body, 'Le besoin #1.');
    assert.equal(d.issues[3].body, 'Close #1');
    assert.equal(d.avis[0].body, 'Vérifié.');
    // Un commentaire fait du seul pied garderait un corps vide, que GitHub refuse : il reste.
    assert.equal(d.commentaires.find((c) => c.id === 13).body, PIED);
  });

  test('un texte sans pied n’est pas réécrit', async () => {
    const { écrits, gh } = api();
    await fusion(gh, 4);
    assert.ok(!écrits.includes('PATCH issues/2'), 'l’issue #2, sans pied, est réécrite');
    assert.ok(!écrits.some((e) => /reviews\/32$/.test(e)), 'une revue sans texte est réécrite');
  });

  test('chaque semaine : toutes les issues et PR, commentaires de revue compris ; un second passage n’écrit rien', async () => {
    const { d, écrits, gh } = api();
    await tout(gh);
    assert.deepEqual(écrits.sort(), [
      'PATCH issues/1',
      'PATCH issues/3',
      'PATCH issues/4',
      'PATCH issues/5',
      'PATCH issues/comments/11',
      'PATCH issues/comments/12',
      'PATCH issues/comments/14',
      'PATCH pulls/comments/21',
      'PATCH pulls/comments/22',
      'PUT pulls/3/reviews/31',
    ]);
    assert.equal(d.issues[2].body, 'Le besoin #2, sans pied.');
    écrits.length = 0;
    await tout(gh);
    assert.deepEqual(écrits, []);
  });
});

// ─── Quand le nettoyage tourne ───────────────────────────────────────────────────────────────────

const WORKFLOW = readFileSync(join(RACINE, '.github/workflows/nettoyage.yml'), 'utf8').replace(/\r\n?/g, '\n');
const jouées = (github) =>
  jouer(WORKFLOW, { github, vars: {}, secrets: {}, inputs: {} })
    .filter((j) => j.tourne)
    .flatMap((j) => j.joués.map(commande));
const PR = (autres) => ({ number: 7, draft: false, body: 'Close #6', merged: false, ...autres });
const fermée = (pr) => ({ event_name: 'pull_request_target', event: { action: 'closed', pull_request: PR(pr) } });

describe('[niveau 4] #254 · quand le nettoyage tourne, et avec quoi', () => {
  test('à la fusion d’une PR : la PR et ses issues ; chaque semaine : tout le projet', () => {
    const fusion = jouées(fermée({ merged: true }));
    assert.ok(fusion.some((c) => /retirer-pied\.mjs fusion "\$PR"/.test(c)), 'la fusion ne nettoie pas la PR');
    assert.ok(!fusion.some((c) => /retirer-pied\.mjs tout/.test(c)), 'la fusion nettoie tout le projet');
    const semaine = jouées({ event_name: 'schedule', event: { schedule: '23 4 * * 1' } });
    assert.ok(semaine.some((c) => /retirer-pied\.mjs tout/.test(c)), 'le passage hebdomadaire ne nettoie pas tout le projet');
    assert.match(WORKFLOW, /^ {2}schedule:\n {4}- cron: '\d+ \d+ \* \* [0-6]'$/m, 'le passage n’est pas hebdomadaire');
  });

  test('une PR fermée sans fusion n’est pas nettoyée, un brouillon non plus', () => {
    assert.deepEqual(jouées(fermée({ merged: false })), []);
    assert.deepEqual(jouées(fermée({ merged: false, draft: true })), []);
    for (const action of ['opened', 'synchronize', 'reopened', 'edited', 'converted_to_draft']) {
      assert.deepEqual(jouées({ event_name: 'pull_request_target', event: { action, pull_request: PR({ draft: true }) } }), [], action);
    }
  });

  test('rien de la PR n’est extrait ; le jeton du job seul, qui lit le dépôt et écrit les issues et les PR', () => {
    assert.match(WORKFLOW, /^on:\n {2}pull_request_target:\n {4}types: \[closed\]\n {2}schedule:\n/m, 'déclencheurs inattendus');
    assert.match(WORKFLOW, /^permissions: \{\}$/m);
    assert.match(WORKFLOW, /\n {4}permissions:\n {6}contents: read\n {6}issues: write\n {6}pull-requests: write\n {4}\S/);
    assert.match(WORKFLOW, /uses: actions\/checkout@v4\n {8}with:\n {10}ref: main\n/);
    assert.doesNotMatch(WORKFLOW, /secrets\.|head\.(?:sha|ref)|pnpm|npm |refs\/pull/);
    assert.match(WORKFLOW, /GH_TOKEN: \$\{\{ github\.token \}\}/);
  });
});
